# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Editor.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os

path=os.getcwd()+"\\icons\\"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1234, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(0, 0, 41, 31))
        self.toolButton.setObjectName("toolButton")
        self.toolButton.setIcon(QtGui.QIcon(path+'application_edit.png'))
        self.toolButton.setDisabled(True)
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(40, 0, 41, 31))
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_2.setIcon(QtGui.QIcon(path+'cog_edit.png'))
        self.toolButton_2.setDisabled(True)
        self.toolButton_3 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_3.setGeometry(QtCore.QRect(80, 0, 41, 31))
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_3.setIcon(QtGui.QIcon(path+'page_paste.png'))
        self.toolButton_3.setDisabled(True)
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(120, 0, 41, 31))
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_4.setIcon(QtGui.QIcon(path+'cut.png'))
        self.toolButton_4.setDisabled(True)
        self.toolButton_5 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_5.setGeometry(QtCore.QRect(160, 0, 41, 31))
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_5.setIcon(QtGui.QIcon(path+'page_copy.png'))
        self.toolButton_5.setDisabled(True)
        self.toolButton_6 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_6.setGeometry(QtCore.QRect(200, 0, 41, 31))
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_6.setIcon(QtGui.QIcon(path+'textfield_delete.png'))
        self.toolButton_6.setDisabled(True)
        self.toolButton_7 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_7.setGeometry(QtCore.QRect(240, 0, 41, 31))
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_7.setIcon(QtGui.QIcon(path+'page_white_copy.png'))
        self.toolButton_7.setDisabled(True)
        self.toolButton_8 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_8.setGeometry(QtCore.QRect(280, 0, 41, 31))
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_8.setIcon(QtGui.QIcon(path+'page_white_paste.png'))
        self.toolButton_8.setDisabled(True)
        self.toolButton_9 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_9.setGeometry(QtCore.QRect(620, 0, 41, 31))
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_9.setIcon(QtGui.QIcon(path+'arrow_refresh.png'))
        self.toolButton_10 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_10.setGeometry(QtCore.QRect(660, 0, 41, 31))
        self.toolButton_10.setObjectName("toolButton_10")
        self.toolButton_10.setIcon(QtGui.QIcon(path+'arrow_in.png'))
        self.toolButton_11 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_11.setGeometry(QtCore.QRect(700, 0, 41, 31))
        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_11.setDisabled(True)
        self.toolButton_11.setIcon(QtGui.QIcon(path+'arrow_out.png'))
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 30, 1232, 615))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 2, 1, 1)
        self.treeView = QtWidgets.QTreeWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setObjectName("treeView")
        self.treeView.headerItem().setText(0, '')
        self.gridLayout.addWidget(self.treeView, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1131, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menu_2)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_PDF = QtWidgets.QAction(MainWindow)
        self.action_PDF.setObjectName("action_PDF")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_PDF)
        self.menu_3.addAction(self.action_8)
        self.menu_3.addAction(self.action_9)
        self.menu_3.addAction(self.action_10)
        self.menu_2.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.menu_3.menuAction())
        self.menu_2.addAction(self.action_11)
        self.menu_2.addAction(self.action_12)
        self.menu_2.addAction(self.action_13)
        self.menu_2.addAction(self.action_14)
        self.menu_2.addAction(self.action_15)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton.setStatusTip('Переименовать узел')
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setStatusTip('Изменить тип узла')
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setStatusTip('Вставить...')
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setStatusTip('Вырезать')
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_5.setStatusTip('Копировать')
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.toolButton_6.setStatusTip('Удалить')
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.toolButton_7.setStatusTip('Копировать значение')
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.toolButton_8.setStatusTip('Вставить значение')
        self.toolButton_9.setStatusTip('Синхронизировать')
        self.toolButton_10.setStatusTip('Минифицировать')
        self.toolButton_11.setStatusTip('Форматировать')
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Редактирование"))
        self.menu_2.setDisabled(True)
        self.menu_3.setTitle(_translate("MainWindow", "Вставить ..."))
        self.menu_3.setDisabled(True)
        self.action.setText(_translate("MainWindow", "Создать"))
        self.action_2.setText(_translate("MainWindow", "Открыть"))
        self.action_3.setText(_translate("MainWindow", "Сохранить"))
        self.action_4.setText(_translate("MainWindow", "Сохранить как ..."))
        self.action_PDF.setText(_translate("MainWindow", "Экспорт в PDF"))
        self.action_5.setText(_translate("MainWindow", "Переименовать узел"))
        self.action_6.setText(_translate("MainWindow", "Изменить тип узла"))
        self.action_8.setText(_translate("MainWindow", "Перед"))
        self.action_9.setText(_translate("MainWindow", "Внутрь"))
        self.action_10.setText(_translate("MainWindow", "После"))
        self.action_11.setText(_translate("MainWindow", "Вырезать"))
        self.action_12.setText(_translate("MainWindow", "Копировать"))
        self.action_13.setText(_translate("MainWindow", "Удалить"))
        self.action_14.setText(_translate("MainWindow", "Копировать значение"))
        self.action_15.setText(_translate("MainWindow", "Вставить значение"))
        self.action_15.setDisabled(True)